# Generated by Django 2.2 on 2020-03-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ManyToManyField(related_name='messages', to='user_app.User'),
        ),
    ]
