# Generated by Django 2.2 on 2020-03-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200322_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_app.User'),
            preserve_default=False,
        ),
    ]
