# Generated by Django 2.2 on 2020-03-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_message_user_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='user_app.User'),
        ),
    ]
